### ISSUE TITLE
db: investigate which DB and ORM to use

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/website-niaefeup-backend-old#2]
Right now, we're using JPA and a simple H2 database for development. We should decide if we want a SQL or Mongo DB and whether it makes sense to keep using JPA or not

**Comment by Jumaruba** [comment]
What about OOD databases? It is much faster than ORM, since it discards the necessity of join operations and consumes less space than NoSQL MongoDB. This is possible due to the use of pointers. 
The disadvantage is that the syntax is little different from the usual databases.

**Comment by BrunoRosendo** [comment]
> What about OOD databases? It is much faster than ORM, since it discards the necessity of join operations and consumes less space than NoSQL MongoDB. This is possible due to the use of pointers. The disadvantage is that the syntax is little different from the usual databases.

Nice point, I'll take that into consideration and see what'd fit best in Spring Boot. I'll update this issue with some options

**Comment by DoStini** [comment]
We could also consider using MongoDB since we already have some data on our mongodb website database. I dont see a lot of advantages of relational databases for this project

Some of these models could be used. Recruitment and users doesn't seem that it will change a lot https://github.com/NIAEFEUP/Website-NIAEFEUP/tree/develop/src/models
