### ISSUE TITLE
dto: transition to JMapper API

### ISSUE THREAD

**Issue by limwa** [NIAEFEUP/website-niaefeup-backend-old#36]
As discussed in #20, JMapper should be investigated as to if it is a good option to replace our current Dto code. The objectives for the new implementation would be: fewer reflective operations and a cleaner implementation.

Depending on how JMapper generates mappers, a caching strategy should be considered.

**Comment by BrunoRosendo** [comment]
@limwa I'm trying to tackle this issue but I'm having some confusion as to what exactly the advantage of JMapper would be. From what I understood, JMapper (and other similar tools like [ModelMapper](https://modelmapper.org/)) have similar behaviour to ObjectMapper (with more features, but we wouldn't really use them) and they'd still need reflection to get the `class` from the generic type.

I tried looking at alternatives but they all seem to rely either on passing the class in the class constructor or at least declaring mappers for each of the DTOs (e.g. [MapStruct](https://www.baeldung.com/mapstruct)). I know there are some advantages to specific mappers but it's a verbose approach and I think our current implementation still stands. I personally think passing the class to the constructor (redundancy) is less confusing than reflection but I understand the tradeoff and I'm fine with what we have.

@MRita443 Do you have any thoughts about this matter? I know you had some trouble with our DTO when working on an issue of yours. I think the only difference in using the manual mappers' approach would be, for example, converting a list of IDs to a list of Accounts in the mapper itself instead of wherever you are trying to do it right now.

**Comment by BrunoRosendo** [comment]
I decided to open a PR that just simplifies the javadocs we had in the Dto class. It was previously very hard to scroll through the class and nobody would bother to read that much text. However, please discuss the comment above before any merge

**Comment by BrunoRosendo** [comment]
It was explained in a meeting that JMapper's advantage would be performance in converting the Dto to an entity. It's also for cases like this that the library (and others) were created and they might achieve better performance (see https://www.baeldung.com/java-performance-mapping-frameworks)

However, I don't think it's worth it to add another dependency to the project for this reason. If we ever truly need a dedicated mapper, then we should use it in the Dto, but I don't think we're there yet (see discussion in https://www.baeldung.com/java-performance-mapping-frameworks). It seems the most expensive operations are the conversions between JSON and Dto (which always need to happen) and the objectMapper creation, which is only done once since we always get the same bean.
